runtime: php81

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 100

env_variables:
  # Put production environment variables here.
  APP_DEBUG: true
  APP_ENV: production
  APP_KEY: base64:Hxj+LufVkGR06aaMqhYFjlvCF6k+ikpKkvLWHput5mc=
  APP_NAME: "RECYCRAFT"
  LOG_LEVEL: debug
  DB_DATABASE: recycraft
  DB_USERNAME: root
  DB_PASSWORD: recycraft123
  DB_SOCKET: '/cloudsql/recycraft-c22-ps285:asia-southeast2:recycraft-backend'

beta_settings:
  cloud_sql_instances: 'recycraft-c22-ps285:asia-southeast2:recycraft-backend'